version: '3'

services:
  app:
    build: .
    restart: always
    container_name: aruka-app
    ports:
      - '8000:80'
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
      #- ./docker/php/php.ini:/usr/local/etc/php/php.ini
      #- ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      TZ: ${TIMEZONE}
      #PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    extra_hosts:
      - ${EXTRA_HOST_DOCKER}
  mysql:
    image: mysql:8.0
    restart: always
    container_name: aruka-mysql
    # Для разработки, в продакшине убрать
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    container_name: aruka-adminer
    ports:
      - '9090:8080'

volumes:
  mysql_data:
